### ISSUE TITLE
All items should be set when creating/modyfing profile

### ISSUE THREAD

**Issue by qarmin** [Kobzol/cargo-wizard#4]
When creating new profile, after selecting "FastCompile" template, only some of properties are filled and rest probably uses some default values.

The problem is that I don't know which properties are default, so I still need read https://doc.rust-lang.org/cargo/reference/profiles.html, but this project aims to avoid this

![Screenshot from 2024-03-10 20-57-51](https://github.com/Kobzol/cargo-wizard/assets/41945903/7965eba1-6b49-4dbb-b5d7-63f2ab8142c9)

**Comment by Kobzol** [comment]
Hi! That's a good point. I suppose that I assumed that `FastCompile` will be mostly applied to the `dev` profile, but it doesn't have to be, of course. I guess that each template should contain the defaults from its "base" profile (FastCompile from `dev` and the remaining two from `release`). This should be a rather easy change to be made [here](https://github.com/Kobzol/cargo-wizard/blob/main/src/predefined.rs#L29), do you want to send a PR? :) If not, I'll fix it tomorrow.

**Comment by Kobzol** [comment]
https://github.com/Kobzol/cargo-wizard/pull/13 should fix this.
