### ISSUE TITLE
Auto-detect if lld/mold are installed or not, and show better warning

### ISSUE THREAD

**Issue by qarmin** [Kobzol/cargo-wizard#5]
Even if mold is installed I see warning `⚠️  Do not forget to install the mold linker, e.g. using `sudo apt install mold`.`

This warning is visible only at the end, but I think that also should be visible, when selecting lld/mold e.g.

```
  LLD                                      "lld" - installed /usr/bin/lld
  MOLD                                     "mold" - not installed
```

**Comment by Kobzol** [comment]
Good idea! https://github.com/Kobzol/cargo-wizard/issues/5 should resolve this.
