### ISSUE TITLE
Selecting first lld and later mold, duplicates flags in `rustlags`

### ISSUE THREAD

**Issue by qarmin** [Kobzol/cargo-wizard#6]
- create new project
- create/overwrite any profile with lld linker
- save changes
- create/overwrite any profile with mold linker
- save changes 
- rustflags now enables two different linkers

https://github.com/Kobzol/cargo-wizard/assets/41945903/4a08717a-7c9b-4d81-bc49-c4c86e272855

**Comment by Kobzol** [comment]
Yeah, RUSTFLAGS are quite opaque, so I don't know if I want to go through the route of parsing them. You can input `-Clink-args` in several different ways, and even the configuration of the linker can be performed using different flags. So it might not be so easy to detect if a flag is duplicated or not.

That being said, we could probably at least detect our own way of specifying the flag.

**Comment by Kobzol** [comment]
https://github.com/Kobzol/cargo-wizard/pull/15 should make this better.
